---
- name: Deploy monitoring stack
  hosts: orangepi
  become: true
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    cadvisor_port: 8081
    prometheus_port: 9090
    node_exporter_port: 9100
    monitoring_dir: /srv/monitoring
  roles:
    - monitoring
    - grafana
    - mosquitto
    - influxdb
    - telegraf