---

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes 
- name: Create directory for monitoring
  file:
    path: "{{ monitoring_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'

- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ monitoring_dir }}/docker-compose.yml"

- name: Create directories for config's
  file:
    path: "{{ monitoring_dir }}/conf/prometheus"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  with_items:
    - "{{ monitoring_dir }}/conf/prometheus"

- name: Deploy prometheus.yml
  template:
    src: prometheus.yml.j2
    dest: "{{ monitoring_dir }}/conf/prometheus/prometheus.yml"

- name: Run Docker Compose
  community.docker.docker_compose_v2:
    project_src: "{{ monitoring_dir }}"
    state: present

- name: Create monitoring external network
  docker_network:
    name: monitoring_external
    state: present
    
- name: Create monitoring internal network
  docker_network:
    name: monitoring_internal
    state: present

- name: Create monitoring network
  docker_network:
    name: monitoring
    state: present